### ISSUE TITLE
Can't open ninjabrain bot normally

### ISSUE THREAD

**Issue by RankkingSbk** [Ninjabrain1/Ninjabrain-Bot#111]
When I open Ninjabrain Bot, a notification pops up in CMD and then disappears quickly. When I recorded my screen and opened Ninjabrain again, it showed the notification in the attached image. I've tried reinstalling Java, Ninjabrain, and changing the path, but nothing happened. I can only open it using the command `java -jar "D:\Minecraft\Ninjabrain-Bot-1.5.1.jar"` in CMD. I don't want it to be this complicated, so I hope someone can help me out.
![image](https://github.com/user-attachments/assets/b4f7976d-0829-49fc-b23f-595bac35c8d9)

**Comment by Ninjabrain1** [comment]
how are you opening ninjabrain bot? why does it say 1.4.3 in the screenshot when you are trying to open 1.5.1?

**Comment by RankkingSbk** [comment]
> Bạn đang mở Ninjabrain Bot như thế nào? Tại sao nó nói 1.4.3 trong ảnh chụp màn hình khi bạn đang cố gắng mở 1.5.1?

I open Ninjabrain Bot by opening CMD and entering the command java -jar "D:\Minecraft\Ninjabrain-Bot-1.5.1.jar". The reason why the image shows version 1.4.3 is that when I used version 1.5.1, the same issue occurred, but I haven't taken a screenshot of it yet.

**Comment by maskersss** [comment]
are you sure that's actually the command you're using? if i had to guess you were forgetting about the `-jar`
![image](https://github.com/user-attachments/assets/53a8acf2-a567-43ac-a8d2-73aa9e9d4017)

**Comment by maskersss** [comment]
oh wait i half misread what you were saying, i would imagine your `.jar` file associations in windows are messed up, and running https://johann.loefflmann.net/en/software/jarfix/index.html should fix them
