### ISSUE TITLE
Issue with calibration for macOS

### ISSUE THREAD

**Issue by abhinavac** [Ninjabrain1/Ninjabrain-Bot#17]
I am not sure how it works, but while calibrating the copy-paste doesn't seem to work for macOS, it seems to copy the commands, but it doesn't paste the commands to the Minecraft window. Is there a way to solve this?

**Comment by abhinavac** [comment]
I actually have solved the issue, where if you go to the IO, of this file, and then for a macOS version instead of making, the key event press key event VK_Control, if you make it VK_META, it seems to work for macOS.

**Comment by Ninjabrain1** [comment]
thanks for making me aware of this, ill fix it in the next update

**Comment by JINZhao2000** [comment]
I am using it in the system linux, but it doesn't work. Should I change sth ?
