### ISSUE TITLE
Problem of minecraft on the system linux

### ISSUE THREAD

**Issue by JINZhao2000** [Ninjabrain1/Ninjabrain-Bot#19]
I tried to use this plugin with minecraft on the system linux.
I found that when I press "k", the command line will show "/" or "/k" (this may be the problem of minecraft)
Secondly, jnativehook has many wrong keycode and rawcode for linux, so the F3 + C can't be truely detected

**Comment by Ninjabrain1** [comment]
I will look into this further, the fact that it shows "/k" sometimes sounds very weird and it may be a problem with minecraft as you suggest. However, jnativehook isnt used to detect F3+C (unless "Alternative clipboard reader" is enabled in settings), the program simply looks for updates to the clipboard. Can you confirm that "Alternative clipboard reader" is turned off and the bot still has problems detecting F3+C?

**Comment by JINZhao2000** [comment]
I've tested that this application uses the second clipboard (which use ctrl + c/v to copy/paste). So I think it's maybe the problem of keyboard mapping ? I have tried alse the problem of command line, it is really the problem of Minecraft, not the problem of this application(@Mojang ? rofl).

**Comment by Arosity** [comment]
![image](https://user-images.githubusercontent.com/30477007/164986823-ff155c4e-b88f-4a0f-a94f-43b55fc7dd58.png)
![image](https://user-images.githubusercontent.com/30477007/164986842-151d00f9-8626-4455-aa1b-02a50e72289c.png)

I'm also having the same issue

**Comment by SuperIsakSwahn** [comment]
If you're new to this mod make sure you really make a creativeworld, my########## inventory got cleared

**Comment by SuperIsakSwahn** [comment]
> If you're new to this mod make sure you really make a creativeworld, my########## inventory got cleared

Oh sorry for swearing

**Comment by aellul27** [comment]
Can confirm. Commands are entered wrong, often with /k / or a command repeated three times. I am using Ubuntu Linux 22.04 with Minecraft Fabric 1.16.1

**Comment by younishd** [comment]
+1

**Comment by Whop42** [comment]
i'm also having this problem (arch linux, 1.16.1 (w/ fabric 14+))

**Comment by Whop42** [comment]
it seems to be using "k" instead of "/" in secondary commands
![image](https://user-images.githubusercontent.com/66795817/219516716-afc13bca-6ef2-4bd0-ac56-6b25497203a7.png)

**Comment by GroobleDierne** [comment]
@JINZhao2000 should be fixed with version 1.4.2

**Comment by Ninjabrain1** [comment]
should be fixed version 1.4.2
