### ISSUE TITLE
Inaccurate Trangulation

### ISSUE THREAD

**Issue by Eimerplayz127** [Ninjabrain1/Ninjabrain-Bot#2]
Ive been trying this for about an hour or three and about 2/5 times I throw an eye The stronghold triangulation is inaccurate. Even though I wasnt moving and sometimes It would be inaccurate for about 2000 blocks

**Comment by Ninjabrain1** [comment]
post a screenshot or video of when you aim at an eye and press f3+c, its most likely wrong because you aim at the wrong place.

**Comment by Eimerplayz127** [comment]
![2021-12-10_16 04 11](https://user-images.githubusercontent.com/95905991/145539144-150e56ca-5099-43cf-bb1c-da201d6de50e.png)

**Comment by Ninjabrain1** [comment]
youre aiming too far to the left, you need to aim here 
![image](https://user-images.githubusercontent.com/8936978/145540157-42b6a0d2-bff8-4339-8f27-acdcacdf8d14.png)

also i dont know if you are using 1 throw or more, but with 1 throw you shouldnt expect to hit it every time

**Comment by Eimerplayz127** [comment]
Even if so how do I get the exact angle of the eye to not make it inaccurate

**Comment by Ninjabrain1** [comment]
Read the "Measuring eyes" section of the perfect travel document
https://docs.google.com/document/d/1JTMOIiS-Hl6_giEB0IQ5ki7UV-gvUXnNmoxhYoSgEAA/edit#heading=h.7c82c3quwosw
