### ISSUE TITLE
Are divine coords for 0divine correct 

### ISSUE THREAD

**Issue by simeguy** [Ninjabrain1/Ninjabrain-Bot#20]
I'm pretty sure I didn't mess up the F3+c part and it sent me to coords for divine 3 and not 0.  If you don't have seed with divine 0 to check here is a seed: 2108312397911699510.  
![Screenshot (253)](https://user-images.githubusercontent.com/102185018/159564366-f36210fb-1959-4b0f-b083-c5101bca29fe.png)

**Comment by Ninjabrain1** [comment]
F3+C is for getting blind coords, if you want divine coords you have to press F3+I while looking at the fossil start
