### ISSUE TITLE
Language selection in settings

### ISSUE THREAD

**Issue by RedLime** [Ninjabrain1/Ninjabrain-Bot#23]
Some people want english or other
It would be even more useful if it could change the language in settings

**Comment by Ninjabrain1** [comment]
I think this would be a good idea as well

**Comment by Crsuh2er0** [comment]
So do I.
Some Chinese also want English.

**Comment by LingMuQingYu** [comment]
@Ninjabrain1 @RedLime @Crsuh2er0 
I implemented this feature a long time ago, but recently I was too busy to remember it.

**Comment by LingMuQingYu** [comment]
#28 add Optional language to display
