### ISSUE TITLE
Minor formatting problem

### ISSUE THREAD

**Issue by jamyreaf** [Ninjabrain1/Ninjabrain-Bot#37]
When at coords (-xxxx, -xxx) that are okay for highroll, the "okay for highroll" doesn't show up because there is not enough space. It appears on large scale setting but most people use the small scale.
![ninbot](https://user-images.githubusercontent.com/123283596/213899642-fe2ff8fb-cb2b-45df-9bbc-e0afaa58503e.PNG)

**Comment by Ninjabrain1** [comment]
Thanks for reporting, it has been fixed and will be in the next update.
