### ISSUE TITLE
Hotkey to update distance and angle to suggested strongholds

### ISSUE THREAD

**Issue by Quintium** [Ninjabrain1/Ninjabrain-Bot#39]
Currently the angle and distance to strongholds only update when you measure an eye. It would be nice if after measuring you could press an extra hotkey to update these stats so you know exactly where to go.

**Comment by Ninjabrain1** [comment]
You can do this by pressing F3+c while looking down, it will update the angle and distance. You don't have to look straight down, just below the horizon

**Comment by Quintium** [comment]
That is useful, thanks
