### ISSUE TITLE
the .jar file doesn't want to run on my computer when I try to open it.

### ISSUE THREAD

**Issue by Tijyel** [Ninjabrain1/Ninjabrain-Bot#5]
I gues I need to download something to run it but I have no idea what.

**Comment by Ninjabrain1** [comment]
Try jarfix, https://johann.loefflmann.net/en/software/jarfix/index.html

If you want another solution you can create a batch file that runs the bot, like what is shown in this video https://www.youtube.com/watch?v=yQpfmBHdF9Q

**Comment by Tijyel** [comment]
Thank you!! The jarfix worked.
