### ISSUE TITLE
A Java Exception has occurred

### ISSUE THREAD

**Issue by ThomasFRG** [Ninjabrain1/Ninjabrain-Bot#50]
I have a Java Exception has occurred on ninjabrain bot 1.4.0 with the latest version of Java. But the 1.3.2 work.

**Comment by Ninjabrain1** [comment]
just released 1.4.1, does this fix it? @ThomasFRG 
https://github.com/Ninjabrain1/Ninjabrain-Bot/releases/tag/1.4.1

**Comment by ThomasFRG** [comment]
it's good thanks
