### ISSUE TITLE
window size is smaller when opening with java 8

### ISSUE THREAD

**Issue by mskrss** [Ninjabrain1/Ninjabrain-Bot#52]
also happens on 1.0.0
not really an important issue, ig it's fine this way, still thought i'd open a bug report
![image](https://user-images.githubusercontent.com/97827489/234939666-146a0d12-a8a8-4e69-b3f5-f86dc10b161f.png)
^ on this image, java 8 is on the left and java 17 is on the right

**Comment by Ninjabrain1** [comment]
Interesing, thats very weird, thanks for reporting

**Comment by Ninjabrain1** [comment]
This seems to be caused by the systems DPI scaling. Do you have this set to something other than 100%?
![](https://i.imgur.com/YdpYWPB.png)

**Comment by mskrss** [comment]
oh yeah i have it set to 125%

**Comment by mskrss** [comment]
i tried changing it to 150%:
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/97827489/aea8e9e6-7bf7-4804-bf80-94858b9a6b99)
it's still the same

also windows says that 100% is recommended for me instead of 150%, but it's the same on 100%:
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/97827489/bfd7cef0-0abb-459a-9f10-6887ec613391)

**Comment by mskrss** [comment]
also, should probably clarify, java 8 ninbbot always launched the same size regardless of that setting, and java 17 ninbbot's size increased if i increased this setting
