### ISSUE TITLE
Unable to use "Create new theme"

### ISSUE THREAD

**Issue by AntuZumas** [Ninjabrain1/Ninjabrain-Bot#58]
Not really sure why, I'm not able to use this feature.
I can select others prefabricated themes, but nothing happens when I click the "Create new theme" button.

**Comment by Ninjabrain1** [comment]
Weird, just to make sure, can you scroll down in the themes window? There should be more themes further down, and thats also where your custom themes are created

**Comment by Ninjabrain1** [comment]
@AntuZumas

**Comment by AntuZumas** [comment]
After uninstalling and installing again, seems to work (?)
Thanks anyways
