### ISSUE TITLE
toggle window visibility does not work when using borderless fullscreen and with the options panel open

### ISSUE THREAD

**Issue by tildejustin** [Ninjabrain1/Ninjabrain-Bot#59]
steps to reproduce:
- make minecraft borderless via BorderlessMinecraft
- open Ninjabrain Bot options panel
- focus minecraft
- press toggle window visibility hotkey

expected behavior:
the window is brought to the foreground

actual behavior:
the window is not brought to the foreground

idk why this is only when borderless and with the options panel open, also I hope this isn't only on my end.

**Comment by UltimatTomat** [comment]
I have the the same issue. Was just wondering if you solved it somehow and if so how?

**Comment by Ninjabrain1** [comment]
This might be fixed in 1.4.3, can you check?

**Comment by tildejustin** [comment]
works!
