### ISSUE TITLE
1.4+ Doesn't work on linux

### ISSUE THREAD

**Issue by GroobleDierne** [Ninjabrain1/Ninjabrain-Bot#64]
Hi o/
It appears that since 1.4.0 and and onward, the mod crashes after the loading screen when ran on linux (Pop!_OS 22.04, kernel 6.2.6). The 1.3.2 version works well however.
```
java -jar Ninjabrain-Bot-1.4.1.jar 
[main] Language: Français
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1a2a297f74, pid=39940, tid=39942
#
# JRE version: OpenJDK Runtime Environment (17.0.7+7) (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
# Java VM: OpenJDK 64-Bit Server VM (17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x97f74]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/grooble/Téléchargements/core.39940)
#
# An error report file with more information is saved as:
# /home/grooble/Téléchargements/hs_err_pid39940.log
#
# If you would like to submit a bug report, please visit:
#   Unknown
# The crash happened outside the Java Virtual Machine in native code.

# See problematic frame for where to report the bug.

#
Abandon (core dumped)
```

And here is the log file mentioned in the error

[hs_err_pid37821.log](https://github.com/Ninjabrain1/Ninjabrain-Bot/files/11593814/hs_err_pid37821.log)

Don't hesitate to ask me if you need more details.

**Comment by The-cude** [comment]
Can confirm. I'm using linux mint and I can't seem to get 1.4 working, it just crashes on the loading screen, however 1.3.2 works perfectly

**Comment by Ninjabrain1** [comment]
Debugging linux code is difficult since I use windows, but I found this crash that is very similar and it appears to be related to the splash screen: https://github.com/caprica/vlcj/issues/353 

I've removed the splash screen and hope that fixes it, please try this version and see if it works @GroobleDierne @The-cude 
[ninjabrainbot-1.4.2TEST9.jar.zip](https://github.com/Ninjabrain1/Ninjabrain-Bot/files/11619268/ninjabrainbot-1.4.2TEST9.jar.zip)

**Comment by GroobleDierne** [comment]
> Debugging linux code is difficult since I use windows, but I found this crash that is very similar and it appears to be related to the splash screen: [caprica/vlcj#353](https://github.com/caprica/vlcj/issues/353)
> 
> I've removed the splash screen and hope that fixes it, please try this version and see if it works @GroobleDierne @The-cude [ninjabrainbot-1.4.2TEST9.jar.zip](https://github.com/Ninjabrain1/Ninjabrain-Bot/files/11619268/ninjabrainbot-1.4.2TEST9.jar.zip)

I just tested it and it works well, thank you!

**Comment by Ninjabrain1** [comment]
In the next release ill include a linux-specific version without the splash screen
