### ISSUE TITLE
suggestion - option to disable the +0.5 added to x and y coords in pre-1.13

### ISSUE THREAD

**Issue by tildejustin** [Ninjabrain1/Ninjabrain-Bot#74]
relevant source: https://github.com/Ninjabrain1/Ninjabrain-Bot/blob/ccbaa72d51ef4cccc7945b06f9ce4ac8d58a51db/src/main/java/ninjabrainbot/model/datastate/endereye/InputData1_12.java#L18-L19
Allows more precision in measuring, I don't think there's any issues with this?

**Comment by Ninjabrain1** [comment]
I don't think it will add much, the limiting factor in pre 1.13 is the angle precision, only having one decimal, not the precision in x and z. Inputting decimals for the coordinates will barely improve the accuracy, and I'm pretty sure it's just wasted time.

**Comment by tildejustin** [comment]
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/66330094/0dd093d3-4746-4486-8842-669722fcf91b)
only one test, will do more, but gave a 5% increase in confidence after two eyes, 2% loss after one eye (std 0.01, proper pixel measured)

another test, was third offset (7.1%) on no coord changing version and not on v1.4.1 at all after first eye
![image](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/66330094/443322ef-0f65-444d-b92f-542aa06f4344)

**Comment by tildejustin** [comment]
I think I may have messed up the first one, never used this before :P

**Comment by tildejustin** [comment]
implemented in https://github.com/tildejustin/ninjabrain-bot/commit/9e3d7337b58b4e2803fac0763da1ec3af3139614
