### ISSUE TITLE
when i click the Ninjabrain Bot v1.4.1,i can‘t see the Program interface，but i can see it in the Taskbar and Task Manager.

### ISSUE THREAD

**Issue by Ryyk3r** [Ninjabrain1/Ninjabrain-Bot#78]
I used to see this interface and use it， but now

**Comment by krankyy** [comment]
Whats ur specs?
Did you update your drivers before it happened?
Also something may be wrong with your java

**Comment by Ryyk3r** [comment]
I haved install java 8, 11 and 17
it ry to reinstall my java 8, but i still cant start it and  still the same result.
my Cpu is R7 -7735HS,no gpu.
 i did not update my drivers before it happened
i often used finalshell to manage my server，Is it relevant to this?

**Comment by krankyy** [comment]
Idk about finalshell or whay that do but you need to make your ninjabrainbot be opened by newer java(link below)(i guess preferably 17+ because you dont have a gpu), if this doesnt work you can try doing this with other java versions.
https://obsproject.com/kb/minecraft-java-edition-troubleshooting

**Comment by Ryyk3r** [comment]
finally，i reinstall my window 10 and make it.

**Comment by Ninjabrain1** [comment]
This is most likely fixed in 1.4.3

**Comment by Ryyk3r** [comment]
Finally I found that due to CPU L3 Cache.
I can not use it when I turn it on
