### ISSUE TITLE
Ninbot 1.4.2 numpad hotkey issues.

### ISSUE THREAD

**Issue by Greetings1** [Ninjabrain1/Ninjabrain-Bot#86]
Updated to 1.4.2, read that some hotkeys can get messed up, so I went to re-set them. Realised that you (at least for me) can't set numpad specific number keys as hotkeys.

In 1.4.1 and earlier, I can have a hotkey set to "NumPad-6" or "NumPad-3" etc. I try to set this back up in 1.4.2, pressing numpad 3 when binding a key, and the only thing that appears in the hotkey window is "3", and my "normal" 3 key (the one over W/E) now ALSO triggers that function. (which is an issue because hotbar / piechart)

I assume this isn't intended?

"Non-numpad-number" keys work fine from what I can tell. This includes some keys like numpad+ and numpad-, although they're called "0xe4e" and "0xe4a" respectively in ninbot hotkey menu, which I assume is like the ahk "code" for the keys?

**Comment by zhz0704** [comment]
I'm having the same issue as well, and I found a really simple workaround for it. Rebind your numpad keys to other keys that work fine, and set those keys in the calculator. I use function keys above F12 so I don't accidentally press them.

**Comment by Ninjabrain1** [comment]
Fixed in 1.4.3
