### ISSUE TITLE
Ninjabrain bot isn't working on main monitor

### ISSUE THREAD

**Issue by KAkos1220** [Ninjabrain1/Ninjabrain-Bot#90]
The program is working completely fine on my secondary monitor, but if I drag it onto my main monitor, it's stops working. 
The problem isn't exits on 1.3.2 or older versions.
Here's a quick video of it:
https://1drv.ms/v/s!Ark72AiNiKhthtZcrthccyaI9TAlXQ?e=Pag4oE

**Comment by Ninjabrain1** [comment]
This should be solved in 1.4.3, can you confirm?

**Comment by KAkos1220** [comment]
It's now working, thank you.
