### ISSUE TITLE
Disable Automatic Update Detection

### ISSUE THREAD

**Issue by Keksiv** [Ninjabrain1/Ninjabrain-Bot#94]
It would be nice to be able to disable automatic update checks/update warnings. I don't want the flashing warning light at all times, and I don't want it making outbound calls with zero way to disable it. I want to be able to check for updates on my own terms and I especially don't want to have to update every time to disable it because then it breaks my batch file.

**Comment by ExeRSolver** [comment]
Is this not what you want?
![Notify Update](https://github.com/Ninjabrain1/Ninjabrain-Bot/assets/114302928/8d0ef091-0b62-4d9a-807c-880a15efade1)

**Comment by Keksiv** [comment]
Unless its just poor wording, this implies that it still makes outbound calls which is far less than preferable.

**Comment by Ninjabrain1** [comment]
If you enable that setting then no outside calls are made. I'd consider it a bug if it still made outside calls since the info is not used for anything.
